### ISSUE TITLE
Can it be run in Editor?

### ISSUE THREAD

**Issue by mruce** [voximplant/unity_sdk_demo#2]
I'm trying to run the sample in editor - is it possible atm? ClientUnityEditor doesn't seem to be properly implemented (lots of NotImplementedExceptions).
Can it be tested inside Editor?

**Comment by niveuseverto** [comment]
Greetings,

ClientUnityEditor is only a stub for api hinting for IDEs. We have no plans to completely implement APIs for this renderer.
