### ISSUE TITLE
Missing prefabs, no version compatibility specified for this

### ISSUE THREAD

**Issue by DeadZen** [voximplant/unity_sdk_demo#3]

**Comment by DeadZen** [comment]
Verified on 2018, theres no missing prefabs, but the Main Camera has Missing Scripts.. any idea what those scripts should be?

**Comment by YuliaGrigorieva** [comment]
Hello @DeadZen ,

Thank you for pointing to the issue. It seems it was caused by missing meta files in CustomCameraDemo project. 

The project is updated.

Please let me know if you face any other issues.

Best regards,
Yulia Grigorieva
